<?xml version="1.0" encoding="utf-8"?><Database Name="QL_VETAU" Class="QuanLyVeTauDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ChiTietLichTrinh" Member="ChiTietLichTrinhs">
    <Type Name="ChiTietLichTrinh">
      <Column Name="MaChiTiet" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLichTrinh" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaGa" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Stt_Ga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianDiChuyenTuTramTruoc" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="KhoangCachTuTramTruoc" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="ChiTietLichTrinh_Ve" Member="Ves" ThisKey="MaChiTiet" OtherKey="DiemDen" Type="Ve" />
      <Association Name="ChiTietLichTrinh_Ve1" Member="Ves1" ThisKey="MaChiTiet" OtherKey="DiemDi" Type="Ve" />
      <Association Name="Ga_ChiTietLichTrinh" Member="Ga" ThisKey="MaGa" OtherKey="MaGa" Type="Ga" IsForeignKey="true" />
      <Association Name="LichTrinhTau_ChiTietLichTrinh" Member="LichTrinhTau" ThisKey="MaLichTrinh" OtherKey="MaLichTrinh" Type="LichTrinhTau" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="MaChucVu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="ChucVu_NhanVien" Member="NhanViens" ThisKey="MaChucVu" OtherKey="MaChucVu" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.Ga" Member="Gas">
    <Type Name="Ga">
      <Column Name="MaGa" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGa" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Ga_ChiTietLichTrinh" Member="ChiTietLichTrinhs" ThisKey="MaGa" OtherKey="MaGa" Type="ChiTietLichTrinh" />
    </Type>
  </Table>
  <Table Name="dbo.HanhLy" Member="HanhLies">
    <Type Name="HanhLy">
      <Column Name="MaHanhLy" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaVe" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="KhoiLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Ve_HanhLy" Member="Ve" ThisKey="MaVe" OtherKey="MaVe" Type="Ve" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHoaDon" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhach" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhuyenMai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Decimal(19,2) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianLapHoaDon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HoaDon_Ve" Member="Ves" ThisKey="MaHoaDon" OtherKey="MaHoaDon" Type="Ve" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="MaKhach" OtherKey="MaKhach" Type="KhachHang" IsForeignKey="true" />
      <Association Name="KhuyenMai_HoaDon" Member="KhuyenMai" ThisKey="MaKhuyenMai" OtherKey="MaKhuyenMai" Type="KhuyenMai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhach" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NamSinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="MaKhach" OtherKey="MaKhach" Type="HoaDon" />
      <Association Name="KhachHang_PhanHoi" Member="PhanHois" ThisKey="MaKhach" OtherKey="MaKhach" Type="PhanHoi" />
      <Association Name="KhachHang_TaiKhoan" Member="TaiKhoans" ThisKey="Email" OtherKey="Email" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.Khoang" Member="Khoangs">
    <Type Name="Khoang">
      <Column Name="MaKhoang" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaToa" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoKhoang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoChoNgoiToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoChoNgoiConLai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Khoang_Ve" Member="Ves" ThisKey="MaKhoang" OtherKey="MaKhoang" Type="Ve" />
      <Association Name="Toa_Khoang" Member="Toa" ThisKey="MaToa" OtherKey="MaToa" Type="Toa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhuyenMai" Member="KhuyenMais">
    <Type Name="KhuyenMai">
      <Column Name="MaKhuyenMai" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhuyenMai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SoTienGiamToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhanTramGiam" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongConLai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhuyenMai_HoaDon" Member="HoaDons" ThisKey="MaKhuyenMai" OtherKey="MaKhuyenMai" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuDoiTraVe" Member="LichSuDoiTraVes">
    <Type Name="LichSuDoiTraVe">
      <Column Name="MaLichSu" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaVe" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HanhDong" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LePhi" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Ve_LichSuDoiTraVe" Member="Ve" ThisKey="MaVe" OtherKey="MaVe" Type="Ve" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichTrinhTau" Member="LichTrinhTaus">
    <Type Name="LichTrinhTau">
      <Column Name="MaLichTrinh" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLichTrinh" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LichTrinhTau_ChiTietLichTrinh" Member="ChiTietLichTrinhs" ThisKey="MaLichTrinh" OtherKey="MaLichTrinh" Type="ChiTietLichTrinh" />
      <Association Name="LichTrinhTau_NhatKyTau" Member="NhatKyTaus" ThisKey="MaLichTrinh" OtherKey="MaLichTrinh" Type="NhatKyTau" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiToa" Member="LoaiToas">
    <Type Name="LoaiToa">
      <Column Name="MaLoaiToa" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiToa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GiaMacDinh" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="CoDieuHoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="LoaiToa_Toa" Member="Toas" ThisKey="MaLoaiToa" OtherKey="MaLoaiToa" Type="Toa" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaChucVu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CCCD" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Luong" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="NhanVien_PhanCong" Member="PhanCongs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="PhanCong" />
      <Association Name="NhanVien_TaiKhoanNhanVien" Member="TaiKhoanNhanViens" ThisKey="Email" OtherKey="Email" Type="TaiKhoanNhanVien" />
      <Association Name="ChucVu_NhanVien" Member="ChucVu" ThisKey="MaChucVu" OtherKey="MaChucVu" Type="ChucVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhatKyTau" Member="NhatKyTaus">
    <Type Name="NhatKyTau">
      <Column Name="MaNhatKy" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTau" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaLichTrinh" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgayGio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NhatKyTau_PhanCong" Member="PhanCongs" ThisKey="MaNhatKy" OtherKey="MaNhatKy" Type="PhanCong" />
      <Association Name="NhatKyTau_Ve" Member="Ves" ThisKey="MaNhatKy" OtherKey="MaNhatKy" Type="Ve" />
      <Association Name="LichTrinhTau_NhatKyTau" Member="LichTrinhTau" ThisKey="MaLichTrinh" OtherKey="MaLichTrinh" Type="LichTrinhTau" IsForeignKey="true" />
      <Association Name="Tau_NhatKyTau" Member="Tau" ThisKey="MaTau" OtherKey="MaTau" Type="Tau" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanCong" Member="PhanCongs">
    <Type Name="PhanCong">
      <Column Name="MaPhanCong" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhatKy" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_PhanCong" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="NhatKyTau_PhanCong" Member="NhatKyTau" ThisKey="MaNhatKy" OtherKey="MaNhatKy" Type="NhatKyTau" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanHoi" Member="PhanHois">
    <Type Name="PhanHoi">
      <Column Name="MaPhanHoi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhach" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NgayPhanHoi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_PhanHoi" Member="KhachHang" ThisKey="MaKhach" OtherKey="MaKhach" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="MaTaiKhoan" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DaXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KhachHang_TaiKhoan" Member="KhachHang" ThisKey="Email" OtherKey="Email" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoanNhanVien" Member="TaiKhoanNhanViens">
    <Type Name="TaiKhoanNhanVien">
      <Column Name="MaTaiKhoan" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NhanVien_TaiKhoanNhanVien" Member="NhanVien" ThisKey="Email" OtherKey="Email" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tau" Member="Taus">
    <Type Name="Tau">
      <Column Name="MaTau" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tau_NhatKyTau" Member="NhatKyTaus" ThisKey="MaTau" OtherKey="MaTau" Type="NhatKyTau" />
      <Association Name="Tau_Toa" Member="Toas" ThisKey="MaTau" OtherKey="MaTau" Type="Toa" />
    </Type>
  </Table>
  <Table Name="dbo.Toa" Member="Toas">
    <Type Name="Toa">
      <Column Name="MaToa" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTau" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoToa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiToa" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Toa_Khoang" Member="Khoangs" ThisKey="MaToa" OtherKey="MaToa" Type="Khoang" />
      <Association Name="LoaiToa_Toa" Member="LoaiToa" ThisKey="MaLoaiToa" OtherKey="MaLoaiToa" Type="LoaiToa" IsForeignKey="true" />
      <Association Name="Tau_Toa" Member="Tau" ThisKey="MaTau" OtherKey="MaTau" Type="Tau" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="MaVe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhatKy" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="MaHoaDon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GiaVe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoang" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Stt_Ghe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiemDi" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DiemDen" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DaThuHoi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Ve_HanhLy" Member="HanhLies" ThisKey="MaVe" OtherKey="MaVe" Type="HanhLy" />
      <Association Name="Ve_LichSuDoiTraVe" Member="LichSuDoiTraVes" ThisKey="MaVe" OtherKey="MaVe" Type="LichSuDoiTraVe" />
      <Association Name="ChiTietLichTrinh_Ve" Member="ChiTietLichTrinh" ThisKey="DiemDen" OtherKey="MaChiTiet" Type="ChiTietLichTrinh" IsForeignKey="true" />
      <Association Name="ChiTietLichTrinh_Ve1" Member="ChiTietLichTrinh1" ThisKey="DiemDi" OtherKey="MaChiTiet" Type="ChiTietLichTrinh" IsForeignKey="true" />
      <Association Name="HoaDon_Ve" Member="HoaDon" ThisKey="MaHoaDon" OtherKey="MaHoaDon" Type="HoaDon" IsForeignKey="true" />
      <Association Name="Khoang_Ve" Member="Khoang" ThisKey="MaKhoang" OtherKey="MaKhoang" Type="Khoang" IsForeignKey="true" />
      <Association Name="NhatKyTau_Ve" Member="NhatKyTau" ThisKey="MaNhatKy" OtherKey="MaNhatKy" Type="NhatKyTau" IsForeignKey="true" />
    </Type>
  </Table>
</Database>